steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
    
- task: DotNetCoreCLI@2
  inputs:
     command: 'restore'
     projects: 'EdgeDB.sln'
     feedsToUse: 'select'
     verbosityRestore: 'Minimal'
  displayName: Restore packages

- script: dotnet build "EdgeDB.Net.sln" --no-restore -v minimal -c $(buildConfiguration) /p:BuildNumber=$(buildNumber) /p:IsTagBuild=$(buildTag)
  displayName: Build projects

- script: dotnet test "test/EdgeDB.Net.Tests.Unit/EdgeDB.Net.Tests.Unit.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) --logger trx
  displayName: Unit Tests

- script: dotnet test "test/EdgeDB.Net.Tests.Integration/EdgeDB.Net.Tests.Integration.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) --logger trx
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))

- task: PublishTestResults@2
  displayName: Publish test results
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
