# Incomplete

name: publish

on:
  push:
    branches:
    - doesnt-exists

jobs:
  publish:
    needs: tests
    runs-on: ubuntu-latest
    name: Run test suite
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Pack projects
      run: |
      dotnet pack "src\EdgeDB.Net.Driver\EdgeDB.Net.Driver.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)" /p:BuildNumber=$(buildNumber) /p:IsTagBuild=$(buildTag)
      dotnet pack "src\EdgeDB.Net.QueryBuilder\EdgeDB.Net.QueryBuilder.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) -o "$(Build.ArtifactStagingDirectory)" /p:BuildNumber=$(buildNumber) /p:IsTagBuild=$(buildTag)
